name: Java CI with Maven

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest  # GitHub Actions uses Ubuntu for builds

    steps:
      - name: Check out the repository
        uses: actions/checkout@v2  # This action checks out your code

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          java-version: '21'  # Set up JDK 21

      - name: Cache Maven dependencies
        uses: actions/cache@v3   # Updated to v3
        with:
          path: ~/.m2/repository  # Cache Maven dependencies
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Build with Maven
        run: mvn clean install --no-transfer-progress  # Run Maven build
